#!/usr/bin/awk -f
# function
function rep_with() {
    gsub("Borum","Dewan Perkasa")
    gsub("stertus","status")
    gsub("panah","bawah")
    gsub("sinang","senang")
    gsub("filtret","filter")
    gsub("reshedul","reshedule")
    gsub("boom","bom")
    gsub("lepih","lebih")
    gsub("Cik Mota","En. Mokhtar")
    gsub("Coba","Cuba")
    gsub("bodeg","bodek")
    gsub("cik","En.")
    gsub("perkenaan","berkenaan")
    gsub("arap-arap","harap")
    gsub("perhati","puas hati")
    gsub("Jumaan","Jumaat")
    gsub("riba","remain")
    gsub("EJK","AJK")
    gsub("pengusahaan","pengurusan")
    gsub("pengurul","pengurus")
    gsub("fanzil","function")
    gsub("mandir","Monday")
    gsub("chat","cat")
    gsub("perpamaian","payment")
    gsub("roskan","uruskan")
    gsub("romandan","Ramadan")
    gsub("refresh","request")
    gsub("tak pergi","tak beri")
    gsub("polisir","confused")
    gsub("cik berhampir","En. Ibrahim")
    gsub("food friend","full strength")
    gsub("dia MP","DMP")
    gsub("tak lawan","tak tahu")
    gsub("Bending","pending")
    gsub("mobile","Obai")
    gsub("obile","Obai")
    gsub("formulator","formal letter")
    gsub("Asking pin","house-keeping")
    gsub("beri sahur","beritahu")
    gsub("maduai","event")
    gsub("marki","maki")
    gsub("skimpy","sekuriti")
    gsub("perhati","puas hati")
    gsub("nak meluat","naik meluat")
    gsub("tanggipul","talipon")
    gsub("berjabat","pejabat")
    gsub("I said","aset")
    gsub("set rumput","0.4")
    gsub("Ali","Hi All")
    gsub("setapi","staffing")
    gsub("FMP","F&B")
    gsub("FME","F&B")
    gsub("Alliance","liase")
    gsub("BXN","BSN")
    gsub("bulat","berbulan")
    gsub("saya buka soap lagi","assalamualikum, selamat pagi")
    gsub("Stuffing","Staffing")
    gsub("Syarat","Mesyuarat")
    gsub("Misyarah","Mesyuarat")
    gsub("kodilasi","koordinasi")
    gsub("manhorm","penthouse")
    gsub("jadian","hari jadi")
    gsub("mid-net","Mindef")
    gsub("BtD","PTD")
    gsub("betang","petang")
    gsub("toste","toast")
    gsub("kekstelan","setelkan")
    gsub("pergi sepijak","beri pinjam")
}
