#!/usr/bin/awk -f
# function
function rep_with() {
    gsub(/\b((mon|tues|wed(nes)?|thur(s)?|fri|sat(ur)?|sun)(day)?)\b)/,"$&")
    gsub(/^H[ou]\w+ing|H[ou]\w+ing/,"Housekeeping")
    gsub(/^[BPF](ina)\w+|[bpf](ina)\w+/,"Finance")
    gsub(/^[SF]\w+l[es]\b/,"Sales")
    gsub(/^F[ro]!i\w+/,"Front Office")
    gsub(/\b[Ff](un)\w+/,"function")
    gsub(/^[Aa]\w+[ae]t/,"Asset")
    gsub(/^[CK]\w+en\b|\b[CK]\w+en\b|ofisier/,"Kitchen")
    gsub(/^Ste\+\b/,"Steward")
    gsub(/Rupiah|(^Rp)/,"RM")
    gsub(/tempat tinggal/,"Homestay")
    gsub(/londry/,"laundri")
    gsub(/[a-z]osak|kong|kaput/,"rosak")
    gsub(/^[Mm[ae]\w+(nt)\w+|\b[Mm[ae]\w+(nt)\w+/,"Maintenance")
    gsub(/[bB]\w+r[ou]+m/,"Dewan Perkasa")
    gsub(/st[a-z]\w+s/,"status")
    gsub(/\b[a-z]\w+wah/,"bawah")
    gsub(/\bsen\w+g/,"senang")
    gsub(/fil[a-z]\w+/,"filter")
    gsub(/\b[a-z]\w+dul/,"reshedule")
    gsub(/\bboom/,"bom")
    gsub(/mandu/,"maklumkan")
    gsub(/dorang/,"dia orang")
    gsub(/\b[Ss]abuk/,"sahur")
    gsub(/\blepih/,"lebih")
    gsub(/M[o][kh][a-z]\w*/,"Mokhtar")
    gsub(/\bC[a-z]ba/,"Cuba")
    gsub(/\bbodeg/,"bodek")
    gsub(/\b[bp]{4,5}\w+an/,"berkenaan")
    gsub(/\b[h]\w+ap/,"berharap")
    gsub(/\bp\w+hati/,"puas hati")
    gsub(/\bJum[a-z]\w+/,"Jumaat")
    gsub(/\briba\b/,"remain")
    gsub(/\b([A-Z]{1})JK/,"AJK")
    gsub(/(F[A-Z]B)/,"F\\&B")
    gsub(/[a-z]\w+uet/,"Banquet")
    gsub(/\bp+an/,"pengurusan")
    gsub(/\bp+urus\b/,"pengurus")
    gsub(/\bmandir/,"Monday")
    gsub(/\bchat/,"cat")
    gsub(/\b[a-z]ive\sin/,"living in")
    gsub(/\bperpamaian/,"payment")
    gsub(/\broskan/,"uruskan")
    gsub(/\b\[Rr]\w+dan\b/,"Ramadan")
    gsub(/\brefresh/,"request")
    gsub(/\btak pergi/,"tak beri")
    gsub(/\bpolisir/,"confused")
    gsub(/\bberhampir/,"En. Ibrahim")
    gsub(/\bfood friend/,"full strength")
    gsub(/D[A-Z]P\b/,"DMP")
    gsub(/\s[NM]C|BNP/," PMC")
    gsub(/ramdin/,"go around")
    gsub(/b[uo]b[uo]\b/,"bubur")
    gsub(/lambok/,"lambuk")
    gsub(/Expiration/,"as per chef")
    gsub(/hurricane|NX/,"Annex Higate")
    gsub(/100 grade/,"under grade")
    gsub(/[dD]e\w[uo]/,"deko")
    gsub(/\btak lawan/,"tak tahu")
    gsub(/\b[a-z]+ding/,"pending")
    gsub(/\b[O][bdp]\w+/,"Obai")
    gsub(/\bformulator/,"formal letter")
    gsub(/\bberi sahur/,"beritahu")
    gsub(/\bmaduai/,"event")
    gsub(/\bmarki/,"maki")
    gsub(/\bleni/,"Lanai")
    gsub(/\bskimpy/,"sekuriti")
    gsub(/\bperhati/,"puas hati")
    gsub(/\bnak meluat/,"naik meluat")
    gsub(/\btanggipul/,"talipon")
    gsub(/\bberjabat/,"pejabat")
    gsub(/\bset rumput/,"0.4")
    gsub(/\bsetapi|starting/,"staffing")
    gsub(/\bpermalator/,"Confirmation Letter")
    gsub(/\bAlliance/,"liase")
    gsub(/\bbulat/,"berbulan")
    gsub(/\bsaya buka soap lagi/,"assalamualaikum, selamat pagi")
    gsub(/\bStuffing/,"Staffing")
    gsub(/mist\w+/,"fogging")
    gsub(/\bM\w+[ht]\b/,"Mesyuarat")
    gsub(/\b(kod)\w+i/,"koordinasi")
    gsub(/[pm]\w+house/,"penthouse")
    gsub(/\bjadian/,"hari jadi")
    gsub(/\bbetang/,"petang")
    gsub(/\btoste/,"toast")
    gsub(/siwik/,"pembekal")
    gsub(/\b\w+st+/,"settle")
    gsub(/\b[A-Z][A-Z]D/,"PTD")
    gsub(/\bcl\w+[cg]/,"clinic")
    gsub(/[Tt]\w+[po][ed]\b/,"thypoid")
    gsub(/\bperiwangan/,"pembelian")
    gsub(/\bRaghani/,"Razali")
    gsub(/\bpenampahan/,"penambahan")
    gsub(/\bbuka water/,"buat order")
    gsub(/\bleek/,"leak")
    gsub(/[0-9],/,/[0-9]/" ,")
    gsub(/\bdiskap/,"discuss")
    gsub(/\bselfie/,"")
    gsub(/\bpenampakan/,"penambahan")
    gsub(/\bada gas/,"ada guest")
    gsub(/\bpart point/,"4.")
    gsub(/\w+ian/,"pengendalian")
    gsub(/peman\w+/,"Pemantau")
    gsub(/Ibarat/,"Imbara")
    gsub(/\bpart 4/,"foyer")
    gsub(/\bpentas ginger/,"F&B Manager")
    gsub(/\bpenyempatan/,"pengesahan")
    gsub(/\bpenyempatan/,"extend")
    gsub(/\bbeter/,"better")
    gsub(/\blocal/,"loker")
    gsub(/\bpecesin/,"purchasing")
    gsub(/\bDelhi/,"daily")
    gsub(/\bLouis Inn/,"living-in")
    gsub(/\bTransi\w/,"Transit")
    #gsub(/\brum\b/,"room")
    gsub(/\bRailover/,"available")
    gsub(/standar/,"standard")
    gsub(/\blo\w+[rl]/,"loker")
    gsub(/\bkejar/,"kerja")
    gsub(/\bbest-lip/,"payslip")
    gsub(/[A-Z]OD\b/,"HOD")
    gsub(/\bMayday/,"Monday")
    gsub(/\bboyar/,"foyer")
    gsub(/\w+cap/,"touch up")
    gsub(/mor[ae]y/,"moreh")
    gsub(/home\w+/,"homestay")
    gsub(/ofiser/,"officer")
    gsub(/pendidik/,"candidate")
    gsub(/lokemart/,"Lokman")
    gsub(/polak/,"fol up")
    gsub(/dilat/,"Deluxe")
    gsub(/wasiat/,"WhatsApp")
    gsub(/aban/,"Oven")
}
