#!/usr/bin/awk -f
# function
function rep_with() {
    gsub("Borum","Dewan Perkasa")
    gsub("stertus","status")
    gsub("panah","bawah")
    gsub("sinang","senang")
    gsub("filtret","filter")
    gsub("reshedul","reshedule")
    gsub("boom","bom")
    gsub("lepih","lebih")
    gsub("Cik Mota","En. Mokhtar")
    gsub("Coba","Cuba")
    gsub("bodeg","bodek")
    gsub("cik","En.")
    gsub("perkenaan","berkenaan")
    gsub("arap-arap","harap")
    gsub("perhati","puas hati")
    gsub("Jumaan","Jumaat")
    gsub("riba","remain")
    gsub("EJK","AJK")
    gsub("DFB","F&B")
    gsub("EMT","ENT")
    gsub("MQD","Banquet")
    gsub("pengusahaan","pengurusan")
    gsub("pengurul","pengurus")
    gsub("fanzil","function")
    gsub("mandir","Monday")
    gsub("chat","cat")
    gsub("db in","living in")
    gsub("perpamaian","payment")
    gsub("roskan","uruskan")
    gsub("romandan","Ramadan")
    gsub("refresh","request")
    gsub("tak pergi","tak beri")
    gsub("polisir","confused")
    gsub("cik berhampir","En. Ibrahim")
    gsub("food friend","full strength")
    gsub("dia MP","DMP")
    gsub("tak lawan","tak tahu")
    gsub("Bending","pending")
    gsub("mobile","Obai")
    gsub("obile","Obai")
    gsub("formulator","formal letter")
    gsub("Asking pin","house-keeping")
    gsub("beri sahur","beritahu")
    gsub("maduai","event")
    gsub("marki","maki")
    gsub("leni","Lanai")
    gsub("skimpy","sekuriti")
    gsub("perhati","puas hati")
    gsub("nak meluat","naik meluat")
    gsub("tanggipul","talipon")
    gsub("berjabat","pejabat")
    gsub("I said","aset")
    gsub("set rumput","0.4")
    gsub("setapi","staffing")
    gsub("permalator","Confirmation Letter")
    gsub("FME","F&B")
    gsub("Alliance","liase")
    gsub("bulat","berbulan")
    gsub("saya buka soap lagi","assalamualikum, selamat pagi")
    gsub("Stuffing","Staffing")
    gsub("Syarat","Mesyuarat")
    gsub("Misyarah","Mesyuarat")
    gsub("kodilasi","koordinasi")
    gsub("manhorm","penthouse")
    gsub("jadian","hari jadi")
    gsub("BtD","PTD")
    gsub("betang","petang")
    gsub("toste","toast")
    gsub("kekstelan","setelkan")
    gsub("pergi sepijak","beri pinjam")
    gsub("panel cleaning","panel clinic")
    gsub("Tai Pond","thypoid")
    gsub("periwangan","pembelian")
    gsub("Raghani","Razali")
    gsub("penampahan","penambahan")
    gsub("buka water","buat order")
    gsub("leek","leak")
    gsub("diskap","discuss")
    gsub("selfie","")
    gsub("penampakan","penambahan")
    gsub("ada gas","ada guest")
    gsub("part point","4.")
    gsub("pendalian","pengendalian")
    gsub("part 4","foyer")
    gsub("pentas ginger","F&B Manager")
    gsub("penyempatan","pengesahan")
    gsub("penyempatan","extend")
    gsub("TIFOT","Thypoid")
    gsub("antar","hantar")
    gsub("beter","better")
}
